var annotated =
[
    [ "fpl", null, [
      [ "Angle", "classfpl_1_1_angle.html", "classfpl_1_1_angle" ],
      [ "BulkSplineEvaluator", "classfpl_1_1_bulk_spline_evaluator.html", "classfpl_1_1_bulk_spline_evaluator" ],
      [ "CompactSpline", "classfpl_1_1_compact_spline.html", "classfpl_1_1_compact_spline" ],
      [ "SplinePlaybackN", "structfpl_1_1_spline_playback_n.html", "structfpl_1_1_spline_playback_n" ],
      [ "QuadraticInitWithStartDerivative", "structfpl_1_1_quadratic_init_with_start_derivative.html", "structfpl_1_1_quadratic_init_with_start_derivative" ],
      [ "QuadraticCurve", "classfpl_1_1_quadratic_curve.html", "classfpl_1_1_quadratic_curve" ],
      [ "CubicInit", "structfpl_1_1_cubic_init.html", "structfpl_1_1_cubic_init" ],
      [ "CubicCurve", "classfpl_1_1_cubic_curve.html", "classfpl_1_1_cubic_curve" ],
      [ "RangeT", "classfpl_1_1_range_t.html", "classfpl_1_1_range_t" ],
      [ "PassThroughVectorConverter", "classfpl_1_1_pass_through_vector_converter.html", "classfpl_1_1_pass_through_vector_converter" ],
      [ "ExternalVectorT", "structfpl_1_1_external_vector_t.html", "structfpl_1_1_external_vector_t" ],
      [ "ExternalVectorT< VectorConverter, 1 >", "structfpl_1_1_external_vector_t_3_01_vector_converter_00_011_01_4.html", "structfpl_1_1_external_vector_t_3_01_vector_converter_00_011_01_4" ],
      [ "ExternalVectorT< VectorConverter, 2 >", "structfpl_1_1_external_vector_t_3_01_vector_converter_00_012_01_4.html", "structfpl_1_1_external_vector_t_3_01_vector_converter_00_012_01_4" ],
      [ "ExternalVectorT< VectorConverter, 3 >", "structfpl_1_1_external_vector_t_3_01_vector_converter_00_013_01_4.html", "structfpl_1_1_external_vector_t_3_01_vector_converter_00_013_01_4" ],
      [ "ExternalVectorT< VectorConverter, 4 >", "structfpl_1_1_external_vector_t_3_01_vector_converter_00_014_01_4.html", "structfpl_1_1_external_vector_t_3_01_vector_converter_00_014_01_4" ],
      [ "InternalVectorT", "structfpl_1_1_internal_vector_t.html", "structfpl_1_1_internal_vector_t" ],
      [ "InternalVectorT< 1 >", "structfpl_1_1_internal_vector_t_3_011_01_4.html", "structfpl_1_1_internal_vector_t_3_011_01_4" ],
      [ "InternalVectorT< 2 >", "structfpl_1_1_internal_vector_t_3_012_01_4.html", "structfpl_1_1_internal_vector_t_3_012_01_4" ],
      [ "InternalVectorT< 3 >", "structfpl_1_1_internal_vector_t_3_013_01_4.html", "structfpl_1_1_internal_vector_t_3_013_01_4" ],
      [ "InternalVectorT< 4 >", "structfpl_1_1_internal_vector_t_3_014_01_4.html", "structfpl_1_1_internal_vector_t_3_014_01_4" ],
      [ "Benchmark", "classfpl_1_1_benchmark.html", "classfpl_1_1_benchmark" ]
    ] ],
    [ "motive", null, [
      [ "MatrixAnim", "classmotive_1_1_matrix_anim.html", "classmotive_1_1_matrix_anim" ],
      [ "MotivatorInit", "classmotive_1_1_motivator_init.html", "classmotive_1_1_motivator_init" ],
      [ "MotiveEngine", "classmotive_1_1_motive_engine.html", "classmotive_1_1_motive_engine" ],
      [ "ModularInit", "classmotive_1_1_modular_init.html", "classmotive_1_1_modular_init" ],
      [ "OvershootInit", "classmotive_1_1_overshoot_init.html", "classmotive_1_1_overshoot_init" ],
      [ "SmoothInit", "classmotive_1_1_smooth_init.html", "classmotive_1_1_smooth_init" ],
      [ "MatrixOperationInit", "structmotive_1_1_matrix_operation_init.html", "structmotive_1_1_matrix_operation_init" ],
      [ "MatrixInit", "classmotive_1_1_matrix_init.html", "classmotive_1_1_matrix_init" ],
      [ "Motivator", "classmotive_1_1_motivator.html", "classmotive_1_1_motivator" ],
      [ "MotivatorVectorTemplate", "classmotive_1_1_motivator_vector_template.html", "classmotive_1_1_motivator_vector_template" ],
      [ "MotivatorMatrix4fTemplate", "classmotive_1_1_motivator_matrix4f_template.html", "classmotive_1_1_motivator_matrix4f_template" ],
      [ "MotiveProcessor", "classmotive_1_1_motive_processor.html", "classmotive_1_1_motive_processor" ],
      [ "MotiveProcessorVector", "classmotive_1_1_motive_processor_vector.html", "classmotive_1_1_motive_processor_vector" ],
      [ "MotiveProcessorMatrix4f", "classmotive_1_1_motive_processor_matrix4f.html", "classmotive_1_1_motive_processor_matrix4f" ],
      [ "MotiveProcessorFunctions", "structmotive_1_1_motive_processor_functions.html", "structmotive_1_1_motive_processor_functions" ],
      [ "MotiveNode1f", "structmotive_1_1_motive_node1f.html", "structmotive_1_1_motive_node1f" ],
      [ "MotiveTarget1f", "classmotive_1_1_motive_target1f.html", "classmotive_1_1_motive_target1f" ],
      [ "MotiveTargetN", "classmotive_1_1_motive_target_n.html", "classmotive_1_1_motive_target_n" ],
      [ "MotiveTargetT", "structmotive_1_1_motive_target_t.html", "structmotive_1_1_motive_target_t" ],
      [ "MotiveTargetT< 1 >", "structmotive_1_1_motive_target_t_3_011_01_4.html", "structmotive_1_1_motive_target_t_3_011_01_4" ],
      [ "MotiveTargetT< 2 >", "structmotive_1_1_motive_target_t_3_012_01_4.html", "structmotive_1_1_motive_target_t_3_012_01_4" ],
      [ "MotiveTargetT< 3 >", "structmotive_1_1_motive_target_t_3_013_01_4.html", "structmotive_1_1_motive_target_t_3_013_01_4" ],
      [ "MotiveTargetT< 4 >", "structmotive_1_1_motive_target_t_3_014_01_4.html", "structmotive_1_1_motive_target_t_3_014_01_4" ],
      [ "MotiveTargetBuilderTemplate", "classmotive_1_1_motive_target_builder_template.html", "classmotive_1_1_motive_target_builder_template" ],
      [ "MotiveTargetBuilderTemplate< VectorConverter, 1 >", "classmotive_1_1_motive_target_builder_template_3_01_vector_converter_00_011_01_4.html", "classmotive_1_1_motive_target_builder_template_3_01_vector_converter_00_011_01_4" ],
      [ "Settled1f", "structmotive_1_1_settled1f.html", "structmotive_1_1_settled1f" ],
      [ "MotiveVersion", "structmotive_1_1_motive_version.html", "structmotive_1_1_motive_version" ]
    ] ],
    [ "Motivator1f", "class_motivator1f.html", null ]
];