var annotated =
[
    [ "motive", null, [
      [ "MatrixAnim", "classmotive_1_1_matrix_anim.html", "classmotive_1_1_matrix_anim" ],
      [ "RigAnim", "classmotive_1_1_rig_anim.html", "classmotive_1_1_rig_anim" ],
      [ "AnimTable", "classmotive_1_1_anim_table.html", "classmotive_1_1_anim_table" ],
      [ "MotivatorInit", "classmotive_1_1_motivator_init.html", "classmotive_1_1_motivator_init" ],
      [ "MotiveEngine", "classmotive_1_1_motive_engine.html", "classmotive_1_1_motive_engine" ],
      [ "ModularInit", "classmotive_1_1_modular_init.html", "classmotive_1_1_modular_init" ],
      [ "OvershootInit", "classmotive_1_1_overshoot_init.html", "classmotive_1_1_overshoot_init" ],
      [ "SmoothInit", "classmotive_1_1_smooth_init.html", "classmotive_1_1_smooth_init" ],
      [ "MatrixOperationInit", "structmotive_1_1_matrix_operation_init.html", "structmotive_1_1_matrix_operation_init" ],
      [ "MatrixOpArray", "classmotive_1_1_matrix_op_array.html", "classmotive_1_1_matrix_op_array" ],
      [ "MatrixInit", "classmotive_1_1_matrix_init.html", "classmotive_1_1_matrix_init" ],
      [ "RigInit", "classmotive_1_1_rig_init.html", "classmotive_1_1_rig_init" ],
      [ "Angle", "classmotive_1_1_angle.html", "classmotive_1_1_angle" ],
      [ "BulkSplineEvaluator", "classmotive_1_1_bulk_spline_evaluator.html", "classmotive_1_1_bulk_spline_evaluator" ],
      [ "CompactSpline", "classmotive_1_1_compact_spline.html", "classmotive_1_1_compact_spline" ],
      [ "SplinePlayback", "structmotive_1_1_spline_playback.html", "structmotive_1_1_spline_playback" ],
      [ "QuadraticInitWithStartDerivative", "structmotive_1_1_quadratic_init_with_start_derivative.html", "structmotive_1_1_quadratic_init_with_start_derivative" ],
      [ "QuadraticCurve", "classmotive_1_1_quadratic_curve.html", "classmotive_1_1_quadratic_curve" ],
      [ "CubicInit", "structmotive_1_1_cubic_init.html", "structmotive_1_1_cubic_init" ],
      [ "CubicCurve", "classmotive_1_1_cubic_curve.html", "classmotive_1_1_cubic_curve" ],
      [ "RangeT", "classmotive_1_1_range_t.html", "classmotive_1_1_range_t" ],
      [ "PassThroughVectorConverter", "classmotive_1_1_pass_through_vector_converter.html", "classmotive_1_1_pass_through_vector_converter" ],
      [ "ExternalVectorT", "structmotive_1_1_external_vector_t.html", "structmotive_1_1_external_vector_t" ],
      [ "ExternalVectorT< VectorConverter, 1 >", "structmotive_1_1_external_vector_t_3_01_vector_converter_00_011_01_4.html", "structmotive_1_1_external_vector_t_3_01_vector_converter_00_011_01_4" ],
      [ "ExternalVectorT< VectorConverter, 2 >", "structmotive_1_1_external_vector_t_3_01_vector_converter_00_012_01_4.html", "structmotive_1_1_external_vector_t_3_01_vector_converter_00_012_01_4" ],
      [ "ExternalVectorT< VectorConverter, 3 >", "structmotive_1_1_external_vector_t_3_01_vector_converter_00_013_01_4.html", "structmotive_1_1_external_vector_t_3_01_vector_converter_00_013_01_4" ],
      [ "ExternalVectorT< VectorConverter, 4 >", "structmotive_1_1_external_vector_t_3_01_vector_converter_00_014_01_4.html", "structmotive_1_1_external_vector_t_3_01_vector_converter_00_014_01_4" ],
      [ "InternalVectorT", "structmotive_1_1_internal_vector_t.html", "structmotive_1_1_internal_vector_t" ],
      [ "InternalVectorT< 1 >", "structmotive_1_1_internal_vector_t_3_011_01_4.html", "structmotive_1_1_internal_vector_t_3_011_01_4" ],
      [ "InternalVectorT< 2 >", "structmotive_1_1_internal_vector_t_3_012_01_4.html", "structmotive_1_1_internal_vector_t_3_012_01_4" ],
      [ "InternalVectorT< 3 >", "structmotive_1_1_internal_vector_t_3_013_01_4.html", "structmotive_1_1_internal_vector_t_3_013_01_4" ],
      [ "InternalVectorT< 4 >", "structmotive_1_1_internal_vector_t_3_014_01_4.html", "structmotive_1_1_internal_vector_t_3_014_01_4" ],
      [ "Motivator", "classmotive_1_1_motivator.html", "classmotive_1_1_motivator" ],
      [ "MotivatorVectorTemplate", "classmotive_1_1_motivator_vector_template.html", "classmotive_1_1_motivator_vector_template" ],
      [ "MatrixMotivator4fTemplate", "classmotive_1_1_matrix_motivator4f_template.html", "classmotive_1_1_matrix_motivator4f_template" ],
      [ "RigMotivator", "classmotive_1_1_rig_motivator.html", "classmotive_1_1_rig_motivator" ],
      [ "MotiveProcessor", "classmotive_1_1_motive_processor.html", "classmotive_1_1_motive_processor" ],
      [ "VectorProcessor", "classmotive_1_1_vector_processor.html", "classmotive_1_1_vector_processor" ],
      [ "MatrixProcessor4f", "classmotive_1_1_matrix_processor4f.html", "classmotive_1_1_matrix_processor4f" ],
      [ "RigProcessor", "classmotive_1_1_rig_processor.html", "classmotive_1_1_rig_processor" ],
      [ "MotiveProcessorFunctions", "structmotive_1_1_motive_processor_functions.html", "structmotive_1_1_motive_processor_functions" ],
      [ "MotiveNode1f", "structmotive_1_1_motive_node1f.html", "structmotive_1_1_motive_node1f" ],
      [ "MotiveTarget1f", "classmotive_1_1_motive_target1f.html", "classmotive_1_1_motive_target1f" ],
      [ "MotiveTargetN", "classmotive_1_1_motive_target_n.html", "classmotive_1_1_motive_target_n" ],
      [ "MotiveTargetT", "structmotive_1_1_motive_target_t.html", "structmotive_1_1_motive_target_t" ],
      [ "MotiveTargetT< 1 >", "structmotive_1_1_motive_target_t_3_011_01_4.html", "structmotive_1_1_motive_target_t_3_011_01_4" ],
      [ "MotiveTargetT< 2 >", "structmotive_1_1_motive_target_t_3_012_01_4.html", "structmotive_1_1_motive_target_t_3_012_01_4" ],
      [ "MotiveTargetT< 3 >", "structmotive_1_1_motive_target_t_3_013_01_4.html", "structmotive_1_1_motive_target_t_3_013_01_4" ],
      [ "MotiveTargetT< 4 >", "structmotive_1_1_motive_target_t_3_014_01_4.html", "structmotive_1_1_motive_target_t_3_014_01_4" ],
      [ "MotiveTargetBuilderTemplate", "classmotive_1_1_motive_target_builder_template.html", "classmotive_1_1_motive_target_builder_template" ],
      [ "MotiveTargetBuilderTemplate< VectorConverter, 1 >", "classmotive_1_1_motive_target_builder_template_3_01_vector_converter_00_011_01_4.html", "classmotive_1_1_motive_target_builder_template_3_01_vector_converter_00_011_01_4" ],
      [ "Benchmark", "classmotive_1_1_benchmark.html", "classmotive_1_1_benchmark" ],
      [ "Settled1f", "structmotive_1_1_settled1f.html", "structmotive_1_1_settled1f" ],
      [ "MotiveVersion", "structmotive_1_1_motive_version.html", "structmotive_1_1_motive_version" ]
    ] ]
];