var annotated =
[
    [ "motive", null, [
      [ "detail", null, [
        [ "CompactSplineNode", "classmotive_1_1detail_1_1_compact_spline_node.html", "classmotive_1_1detail_1_1_compact_spline_node" ]
      ] ],
      [ "MatrixAnim", "classmotive_1_1_matrix_anim.html", "classmotive_1_1_matrix_anim" ],
      [ "RigAnim", "classmotive_1_1_rig_anim.html", "classmotive_1_1_rig_anim" ],
      [ "AnimTable", "classmotive_1_1_anim_table.html", "classmotive_1_1_anim_table" ],
      [ "MotivatorInit", "classmotive_1_1_motivator_init.html", "classmotive_1_1_motivator_init" ],
      [ "MotiveEngine", "classmotive_1_1_motive_engine.html", "classmotive_1_1_motive_engine" ],
      [ "SimpleInit", "structmotive_1_1_simple_init.html", "structmotive_1_1_simple_init" ],
      [ "SimpleInitTemplate", "structmotive_1_1_simple_init_template.html", "structmotive_1_1_simple_init_template" ],
      [ "ConstInit", "structmotive_1_1_const_init.html", "structmotive_1_1_const_init" ],
      [ "EaseInEaseOutInit", "structmotive_1_1_ease_in_ease_out_init.html", "structmotive_1_1_ease_in_ease_out_init" ],
      [ "SpringInit", "structmotive_1_1_spring_init.html", "structmotive_1_1_spring_init" ],
      [ "OvershootInit", "classmotive_1_1_overshoot_init.html", "classmotive_1_1_overshoot_init" ],
      [ "SplineInit", "classmotive_1_1_spline_init.html", "classmotive_1_1_spline_init" ],
      [ "MatrixOperationInit", "structmotive_1_1_matrix_operation_init.html", "structmotive_1_1_matrix_operation_init" ],
      [ "MatrixOpArray", "classmotive_1_1_matrix_op_array.html", "classmotive_1_1_matrix_op_array" ],
      [ "MatrixInit", "classmotive_1_1_matrix_init.html", "classmotive_1_1_matrix_init" ],
      [ "RigInit", "classmotive_1_1_rig_init.html", "classmotive_1_1_rig_init" ],
      [ "Angle", "classmotive_1_1_angle.html", "classmotive_1_1_angle" ],
      [ "BulkSplineEvaluator", "classmotive_1_1_bulk_spline_evaluator.html", "classmotive_1_1_bulk_spline_evaluator" ],
      [ "UncompressedNode", "structmotive_1_1_uncompressed_node.html", "structmotive_1_1_uncompressed_node" ],
      [ "CompactSpline", "classmotive_1_1_compact_spline.html", "classmotive_1_1_compact_spline" ],
      [ "SplinePlayback", "structmotive_1_1_spline_playback.html", "structmotive_1_1_spline_playback" ],
      [ "SplineState", "structmotive_1_1_spline_state.html", "structmotive_1_1_spline_state" ],
      [ "SplineBlend", "structmotive_1_1_spline_blend.html", "structmotive_1_1_spline_blend" ],
      [ "QuadraticInitWithStartDerivative", "structmotive_1_1_quadratic_init_with_start_derivative.html", "structmotive_1_1_quadratic_init_with_start_derivative" ],
      [ "QuadraticInitWithOrigin", "structmotive_1_1_quadratic_init_with_origin.html", "structmotive_1_1_quadratic_init_with_origin" ],
      [ "QuadraticInitWithPoint", "structmotive_1_1_quadratic_init_with_point.html", "structmotive_1_1_quadratic_init_with_point" ],
      [ "QuadraticCurve", "classmotive_1_1_quadratic_curve.html", "classmotive_1_1_quadratic_curve" ],
      [ "CubicInit", "structmotive_1_1_cubic_init.html", "structmotive_1_1_cubic_init" ],
      [ "CubicCurve", "classmotive_1_1_cubic_curve.html", "classmotive_1_1_cubic_curve" ],
      [ "QuadraticEaseInEaseOut", "classmotive_1_1_quadratic_ease_in_ease_out.html", "classmotive_1_1_quadratic_ease_in_ease_out" ],
      [ "QuadraticSpring", "classmotive_1_1_quadratic_spring.html", "classmotive_1_1_quadratic_spring" ],
      [ "IntFloatUnion", "unionmotive_1_1_int_float_union.html", "unionmotive_1_1_int_float_union" ],
      [ "RangeT", "classmotive_1_1_range_t.html", "classmotive_1_1_range_t" ],
      [ "MathFuVectorConverter", "classmotive_1_1_math_fu_vector_converter.html", "classmotive_1_1_math_fu_vector_converter" ],
      [ "VectorT", "structmotive_1_1_vector_t.html", "structmotive_1_1_vector_t" ],
      [ "VectorT< VectorConverter, 1 >", "structmotive_1_1_vector_t_3_01_vector_converter_00_011_01_4.html", "structmotive_1_1_vector_t_3_01_vector_converter_00_011_01_4" ],
      [ "VectorT< VectorConverter, 2 >", "structmotive_1_1_vector_t_3_01_vector_converter_00_012_01_4.html", "structmotive_1_1_vector_t_3_01_vector_converter_00_012_01_4" ],
      [ "VectorT< VectorConverter, 3 >", "structmotive_1_1_vector_t_3_01_vector_converter_00_013_01_4.html", "structmotive_1_1_vector_t_3_01_vector_converter_00_013_01_4" ],
      [ "VectorT< VectorConverter, 4 >", "structmotive_1_1_vector_t_3_01_vector_converter_00_014_01_4.html", "structmotive_1_1_vector_t_3_01_vector_converter_00_014_01_4" ],
      [ "Motivator", "classmotive_1_1_motivator.html", "classmotive_1_1_motivator" ],
      [ "MotivatorNf", "classmotive_1_1_motivator_nf.html", "classmotive_1_1_motivator_nf" ],
      [ "MotivatorXfTemplate", "classmotive_1_1_motivator_xf_template.html", "classmotive_1_1_motivator_xf_template" ],
      [ "MatrixMotivator4fTemplate", "classmotive_1_1_matrix_motivator4f_template.html", "classmotive_1_1_matrix_motivator4f_template" ],
      [ "RigMotivator", "classmotive_1_1_rig_motivator.html", "classmotive_1_1_rig_motivator" ],
      [ "MotiveProcessor", "classmotive_1_1_motive_processor.html", "classmotive_1_1_motive_processor" ],
      [ "MotiveProcessorNf", "classmotive_1_1_motive_processor_nf.html", "classmotive_1_1_motive_processor_nf" ],
      [ "MatrixProcessor4f", "classmotive_1_1_matrix_processor4f.html", "classmotive_1_1_matrix_processor4f" ],
      [ "RigProcessor", "classmotive_1_1_rig_processor.html", "classmotive_1_1_rig_processor" ],
      [ "MotiveProcessorFunctions", "structmotive_1_1_motive_processor_functions.html", "structmotive_1_1_motive_processor_functions" ],
      [ "SimpleProcessorTemplate", "classmotive_1_1_simple_processor_template.html", "classmotive_1_1_simple_processor_template" ],
      [ "MotiveCurveShape", "structmotive_1_1_motive_curve_shape.html", "structmotive_1_1_motive_curve_shape" ],
      [ "MotiveNode1f", "structmotive_1_1_motive_node1f.html", "structmotive_1_1_motive_node1f" ],
      [ "MotiveTarget1f", "classmotive_1_1_motive_target1f.html", "classmotive_1_1_motive_target1f" ],
      [ "MotiveTargetN", "classmotive_1_1_motive_target_n.html", "classmotive_1_1_motive_target_n" ],
      [ "MotiveTargetT", "structmotive_1_1_motive_target_t.html", "structmotive_1_1_motive_target_t" ],
      [ "MotiveTargetT< 1 >", "structmotive_1_1_motive_target_t_3_011_01_4.html", "structmotive_1_1_motive_target_t_3_011_01_4" ],
      [ "MotiveTargetT< 2 >", "structmotive_1_1_motive_target_t_3_012_01_4.html", "structmotive_1_1_motive_target_t_3_012_01_4" ],
      [ "MotiveTargetT< 3 >", "structmotive_1_1_motive_target_t_3_013_01_4.html", "structmotive_1_1_motive_target_t_3_013_01_4" ],
      [ "MotiveTargetT< 4 >", "structmotive_1_1_motive_target_t_3_014_01_4.html", "structmotive_1_1_motive_target_t_3_014_01_4" ],
      [ "MotiveTargetBuilderTemplate", "classmotive_1_1_motive_target_builder_template.html", "classmotive_1_1_motive_target_builder_template" ],
      [ "MotiveTargetBuilderTemplate< VectorConverter, 1 >", "classmotive_1_1_motive_target_builder_template_3_01_vector_converter_00_011_01_4.html", "classmotive_1_1_motive_target_builder_template_3_01_vector_converter_00_011_01_4" ],
      [ "Benchmark", "classmotive_1_1_benchmark.html", "classmotive_1_1_benchmark" ],
      [ "Settled1f", "structmotive_1_1_settled1f.html", "structmotive_1_1_settled1f" ],
      [ "MotiveVersion", "structmotive_1_1_motive_version.html", "structmotive_1_1_motive_version" ]
    ] ],
    [ "MotivatorNfBase", "class_motivator_nf_base.html", null ]
];